#!/usr/bin/env bash
# Bash script that Install nginx on your web-01 server and requirements
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
service nginx start
