#!/usr/bin/env bash
# Configure your Nginx server to redirect /redirect_me to another page.
sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.nginx-debian.html
redirect_url="https://twitter.com/jossvega103"
sudo sed -i "s|rewrite ^/redirect_me .*;|return 301 $redirect_url;|" /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart

